name: .NET CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-2022]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Download Dalamud
      if: "!contains(github.event.head_commit.message, '[stg]')"
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Download Dalamud staging
      if: "contains(github.event.head_commit.message, '[stg]')"
      run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
        
    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build --no-restore src
      
    - name: Test
      run: dotnet test --no-build --verbosity normal src

    - name: Extract Publish
      run: |
        Expand-Archive -Force ./bin/x64/Release.ILMerge/SupineSnail.JobGaugeAdjustments/latest.zip ./Artifact
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: ./Artifact/*