name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: [windows-2022]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
        
    - name: Set VERSION variable from tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      shell: bash

    - name: Download Dalamud
      if: "!contains(github.event.head_commit.message, '[stg]')"
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Download Dalamud staging
      if: "contains(github.event.head_commit.message, '[stg]')"
      run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
        
    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.get_version.outputs.VERSION }} src
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release /p:Version=${{ steps.get_version.outputs.VERSION }} src

    - name: Extract Publish
      run: |
        Expand-Archive -Force ./src/SupineSnail.JobGaugeAdjustments/bin/x64/Release.ILMerge/SupineSnail.JobGaugeAdjustments/latest.zip ./Artifact
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: ./Artifact/*